[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; style-src 'unsafe-inline' *.netlify.app; form-action 'self'; script-src 'self'; connect-src 'self'; img-src 'self' *.cloudinary.com cloudinary.com *.cloudfront.net; base-uri 'self';"

